app/main/models/__init__.py
from . import module
from . import partner
from . import user
from . import model
from . import rule
from . import language
from . import bank
from . import country
from . import currency
from . import company

app/main/models/bank.py
from app import db

class Bank(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    name = db.Column(db.String(60), nullable=False)
    street = db.Column(db.String(60))
    street2 = db.Column(db.String(60))
    zip = db.Column(db.String(60))
    city = db.Column(db.String(60))
    state = db.Column(db.String(60))
    partnerbank_ids = db.relationship("PartnerBank", backref="partnerbanks")
    country_id = db.Column(db.Integer, db.ForeignKey('country.id'))
    


class PartnerBank(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    active = db.Column(db.Boolean, default=True)
    acc_number = db.Column(db.String(30), nullable=False)
    acc_holder_name = db.Column(db.String(30), nullable=False) # Account holder name
    partner_id = db.Column(db.Integer, db.ForeignKey('partner.id'))
    bank_id = db.Column(db.Integer, db.ForeignKey('bank.id'))
    currency_id = db.Column(db.Integer, db.ForeignKey('currency.id'))
    company_id = db.Column(db.Integer, db.ForeignKey('company.id'))

    

app/main/models/company.py
from app import db

import enum

company_users = db.Table('company_users', 
    db.Column('user_id', db.ForeignKey('user.id')),
    db.Column('company_id', db.ForeignKey('company.id'))
)

class BaseOnboardingEnum(enum.Enum):
    not_done = "Not done"
    just_done = "Just done"
    done = "Done"


class FontSelectionEnum(enum.Enum):
    Lato = "Lato"
    Roboto = "Roboto"
    Open_Sans = "Open Sans"
    Montserrat = "Montserrat"
    Oswald = "Oswald"
    Raleway = "Raleway"



class Company(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    name = db.Column(db.String, nullable=False) # Company Name
    sequence = db.Column(db.Integer, default=10) # used to order companies in the company switcher
    parent_id = db.Column(db.Integer, db.ForeignKey('company.id')) # Parent Company
    child_companies = db.relationship("Company", backref=db.backref('Company', remote_side=[id]))
    report_header = db.Column(db.Text) # company tagline
    report_footer = db.Column(db.Text)
    user_ids = db.relationship('User', secondary=company_users, lazy='subquery', backref=db.backref('accepted_users', lazy=True)) 
    street = db.Column(db.String(30))
    street2 = db.Column(db.String(30))
    zip = db.Column(db.String(30))
    city = db.Column(db.String(30))
    partnerbank_ids = db.relationship('PartnerBank', backref='bankaccounts_assosciated_with_this_company')    
    country_id = db.Column(db.Integer, db.ForeignKey('country.id'))
    email = db.Column(db.String(10))
    phone = db.Column(db.String(20))
    website = db.Column(db.String(60))
    vat = db.Column(db.String(15)) # Tax ID
    company_registry = db.Column(db.String(60))
    
    # paperformat_id =
    # external_report_layout_id =
    
    base_onboarding_company_state = db.Column(
        db.Enum(BaseOnboardingEnum),
        default=BaseOnboardingEnum.not_done
    ) # state of onboarding company step
    
    # favicon = 

    font = db.Column(
        db.Enum(FontSelectionEnum),
        default=FontSelectionEnum.Lato
    )
    primary_color = db.Column(db.String(30))
    secondary_color = db.Column(db.String(30))
    currencyrate_ids = db.relationship('CurrencyRate', backref='rates_assosciated_with_this_company')    
    partner_ids = db.relationship('Partner', backref='partner_accounts_linked_to_this_company')


    

app/main/models/country.py
from app import db

import enum

FLAG_MAPPING = {
    "GF": "fr",
    "BV": "no",
    "BQ": "nl",
    "GP": "fr",
    "HM": "au",
    "YT": "fr",
    "RE": "fr",
    "MF": "fr",
    "UM": "us",
}

NO_FLAG_COUNTRIES = [
    "AQ", #Antarctica
    "SJ", #Svalbard + Jan Mayen : separate jurisdictions : no dedicated flag
]

class NamePositionEnum(enum.Enum):
    before = "Before Address"
    after = "After Address"


class Country(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    name = db.Column(db.String(60), nullable=False) # Full country name
    code = db.Column(db.String(5)) # ISO country code

    """
        Display format to use for addresses belonging to this country.\n\n"
             "You can use python-style string pattern with all the fields of the address "
             "(for example, use '%(street)s' to display the field 'street') plus"
             "\n%(state_name)s: the name of the state"
             "\n%(state_code)s: the code of the state"
             "\n%(country_name)s: the name of the country"
             "\n%(country_code)s: the code of the country
    """
    address_format = db.Column(db.Text, nullable=False, default='%(street)s\n%(street2)s\n%(city)s %(state_code)s %(zip)s\n%(country_name)s') 

    # address_view_id =
    
    banks = db.relationship("Bank", backref="banks_found_in_this_country")    
    companies = db.relationship("Company", backref="companies_found_in_this_country")
    currency_id = db.Column(db.Integer, db.ForeignKey('currency.id'))
    image_url = db.Column(db.String(120)) # url of flag image
    phone_code = db.Column(db.Integer) # country calling code
    name_position = db.Column(
        db.Enum(NamePositionEnum),
        default=NamePositionEnum.before
    ) # determine where the customer/company name should be placed i.e before or after address
    vat_label = db.Column(db.String(60)) # use this field if you want to change vat label
    state_required = db.Column(db.Boolean, default=False)
    zip_required = db.Column(db.Boolean, default=True)
    partners = db.relationship("Partner", backref="partners_assosciated_with_this_country")

    
    

app/main/models/currency.py
from app import db

from sqlalchemy import Float
from sqlalchemy.ext.declarative import declared_attr

import re
import enum

CURRENCY_DISPLAY_PATTERN = re.compile(r'(\w+)\s*(?:\((.*)\))?')


class PositionEnum(enum.Enum):
    after = "After Amount"
    before = "Before Amount"    


class Currency(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    name = db.Column(db.String(10), nullable=False) # Currency Code (ISO 4217)
    rate = db.Column(Float)
    rate_ids = db.relationship('CurrencyRate', backref='rates_for_this_currency')
    rounding = db.Column(Float, default=0.01) # rounding factor
    decimal_places = db.Column(db.Integer)
    active = db.Column(db.Boolean, default=True)
    position = db.Column(
        db.Enum(PositionEnum),
        default=PositionEnum.after
    )
    date = db.Column(db.Date)
    currency_unit_label = db.Column(db.String(10)) # currency unit name
    currency_subunit_label = db.Column(db.String(10)) # currency subunit name
    partnerbank_ids = db.relationship('PartnerBank', backref='partner_bank_currencies')
    country_ids = db.relationship('Country', backref='countries_using_this_currency')  
    

    def _compute_current_rate(self):
        pass
    
    def _get_rates(self, company, date):
        pass


class CurrencyRate(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    name = db.Column(db.Date, nullable=False, index=True)
    rate = db.Column(Float, default=1.0) # The rate of the currency to the currency of rate 1
    currency_id = db.Column(db.Integer, db.ForeignKey('currency.id'))
    company_id = db.Column(db.Integer, db.ForeignKey('company.id'))
    

app/main/models/language.py
from app import db, current_app
from config import basedir
from operator import itemgetter

import enum
import os
import csv

DEFAULT_DATE_FORMAT = '%m/%d/%Y'
DEFAULT_TIME_FORMAT = '%H:%M:%S'


class DirectionEnum(enum.Enum):
    ltr = "Left-to-right"
    rtl = "Rigt-to-Left"


class WeekStartEnum(enum.Enum):
    one = "Monday"
    two = "Tuesday"
    three = "Wednesday"
    four = "Thursday"
    five = "Friday"
    six = "Saturday"
    seven = "Sunday"


class Lang(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    name = db.Column(db.String(60), nullable=False)
    # used to get/set locales for user
    code = db.Column(db.String(10), nullable=False)
    # name of the po files to use for translations
    iso_code = db.Column(db.String(10))
    # Lang code displayed in the URL
    url_code = db.Column(db.String(120), nullable=False)
    active = db.Column(db.Boolean)
    directions = db.Column(
        db.Enum(DirectionEnum),
        default=DirectionEnum.ltr,
        nullable=False
    )
    date_format = db.Column(db.String(60), nullable=False,
                            default=DEFAULT_DATE_FORMAT)
    time_format = db.Column(db.String(60), nullable=False,
                            default=DEFAULT_TIME_FORMAT)
    week_start = db.Column(
        db.Enum(WeekStartEnum),
        default=WeekStartEnum.seven,
        nullable=False
    )  # First day of the week

    """ 
    Separator Format. It should be like [,n] where 0 < n :starting from Unit digit.
    -1 will end the separation. e.g [3,2,-1] will represent 106500, to be 1,06,500;
    [1,2,-1] will represent it to be [106,05,0]; [3] will represent it as 106,500.
    Provided ',' as the thousand separator in each case
    """
    grouping = db.Column(db.String(10), nullable=False, default='[]')
    decimal_point = db.Column(
        db.String(5), nullable=False, default='.')  # decimal separator
    thousand_sep = db.Column(db.String(5), nullable=False,
                             default=',')  # thousands separator

    @staticmethod
    def seed_language():
        lang = Lang.query.first()
        if lang is None:
            csv_file = os.path.join(
                basedir, 'app/main/data/language.csv')
            with open(csv_file, 'r') as fin:
                dr = csv.DictReader(fin)
                if 'sqlite' in current_app.config['SQLALCHEMY_DATABASE_URI']:
                    for i in dr:
                        lang = Lang(
                            id=i['id'], name=i['name'], code=i['code'], iso_code=i['iso_code'], url_code=i['url_code'], active=i['_active'], directions=i['direction'], date_format=i['date_format'], time_format=i['time_format'], grouping=i['grouping'], decimal_point=i['decimal_point'], thousand_sep=i['thousands_sep'])
                        db.session.add(lang)
                        db.session.commit()

    def get_installed(self):
        """Return the installed languages as a list of (code, name) sorted by name"""
        langs = self.with_context(activate_test=True).search([])
        return sorted([(lang.code, lang.name) for lang in langs], key=itemgetter(1))

app/main/models/model.py
from app import db

class ModelAccess(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    name = db.Column(db.String(60), nullable=False, index=True)

    # If you uncheck the active field, it will diable the 
    # ACL without deleting it (if you delete a native ACL, 
    # it will be re-created when you reload the module).
    active = db.Column(db.Boolean, default=True)
    model_id = db.Column(db.Integer, db.ForeignKey('model.id'), index=True)
    group_id = db.Column(db.Integer, db.ForeignKey('user_group.id', ondelete='RESTRICT'), index=True)
    perm_read = db.Column(db.Boolean) # Read Access
    perm_write = db.Column(db.Boolean) # Write Access
    perm_create = db.Column(db.Boolean) # Create Access
    perm_unlink = db.Column(db.Boolean) # Delete Access


class Model(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    access_ids = db.relationship('ModelAccess', backref='access_ids_for_this_model')
    rules = db.relationship('Rule', backref='rules_for_this_model')
    
    

app/main/forms.py
from flask import request
from flask_wtf import FlaskForm
from wtforms import StringField, SubmitField, TextAreaField
from wtforms.validators import ValidationError, DataRequired, Length
from flask_babel import _, lazy_gettext as _l
from app.auth.models.employee import Employee


class EditProfileForm(FlaskForm):
    username = StringField(_l('Username'), validators=[DataRequired()])
    about_me = TextAreaField(_l('About me'),
                             validators=[Length(min=0, max=140)])
    submit = SubmitField(_l('Submit'))

    def __init__(self, original_username, *args, **kwargs):
        super(EditProfileForm, self).__init__(*args, **kwargs)
        self.original_username = original_username

    def validate_username(self, username):
        if username.data != self.original_username:
            employee = Employee.query.filter_by(username=self.username.data).first()
            if employee is not None:
                raise ValidationError(_('Please use a different username.'))


class EmptyForm(FlaskForm):
    submit = SubmitField('Submit')


class PostForm(FlaskForm):
    post = TextAreaField(_l('Say something'), validators=[DataRequired()])
    submit = SubmitField(_l('Submit'))


class SearchForm(FlaskForm):
    q = StringField(_l('Search'), validators=[DataRequired()])

    def __init__(self, *args, **kwargs):
        if 'formdata' not in kwargs:
            kwargs['formdata'] = request.args
        if 'csrf_enabled' not in kwargs:
            kwargs['csrf_enabled'] = False
        super(SearchForm, self).__init__(*args, **kwargs)


class MessageForm(FlaskForm):
    message = TextAreaField(_l('Message'), validators=[
        DataRequired(), Length(min=1, max=140)])
    submit = SubmitField(_l('Submit'))

app/main/__init__.py
from flask import Blueprint

bp = Blueprint('main', __name__)

from app.main import routes

app/main/routes.py
from datetime import datetime
from flask import render_template, flash, redirect, url_for, request, g, \
    jsonify, current_app
from flask_login import current_user, login_required
from flask_babel import _, get_locale
# from guess_language import guess_language
from app import db
from app.main.forms import EditProfileForm, EmptyForm, PostForm, SearchForm, \
    MessageForm
from app.auth.models.employee import Employee
from app.main.models.module import Module, ModuleCategory
from app.translate import translate
from app.main import bp
from app.decorators import admin_required


@bp.route('/', methods=['GET', 'POST'])
@login_required
def index():
    return render_template('index.html', title=_('Tool to Grow Your Business | Teleios'))


@bp.route('/new/database')
@login_required
@admin_required
def choose_apps():
    moduleCategories = ModuleCategory.query.join(
        Module, ModuleCategory.id == Module.category_id).filter(Module.enable.is_(True)).all()
    modules = Module.query.filter(Module.enable.is_(True)).all()
    return render_template('main/set-up.html', title=_('New Database | Teleios'), moduleCategories=moduleCategories, modules=modules)


@bp.route('/getting-started/databases')
@login_required
@admin_required
def getting_started():
    return render_template('main/set-up.html', title=_('Getting Started | Teleios'))


@bp.route('/home')
@login_required
def home():
    modules = Module.query.join(ModuleCategory, Module.category_id == ModuleCategory.id).filter(
        Module.installed.is_(True)).all()
    return render_template('main/home.html', title=_('Home | Teleios'), modules=modules)


@bp.route('/module/<id>')
@login_required
def connect(id):
    module = Module.query.filter_by(id=id).first()
    descriptor = module.descriptor
    if descriptor == "accounting":
        return redirect(url_for('accounting.dashboard'))


@bp.route('/dashboard')
@login_required
def dashboard():
    return render_template('main/dashboard.html', title=_('Dashboard | Teleios'))


@bp.route('/all-apps', methods=['GET', 'POST'])
@login_required
def all_apps():
    modulecategories = ModuleCategory.query.all()
    _modules = Module.query.all()
    return render_template('main/apps.html', title=_('Teleios | All Apps'), modulecategories=modulecategories, _modules=_modules, )


@bp.route('/module/<name>', methods=['GET', 'POST'])
@login_required
def _module(name):
    return render_template('base.html', title=_('Teleios | ' + name))


@bp.route('/install_module/<id>', methods=['GET', 'POST'])
@admin_required
def install_module(id):
    """Installs the selected module"""
    # get module details
    module = Module.query.filter_by(id=id).first()
    return "success"

app/templates/main/home.html
{% extends "base.html" %}

{% block content %}
<div class="nk-content-body">
    <div class="nk-content-wrap">
        <div class="nk-block-head nk-block-head-sm">
            <div class="nk-block-between">
                <div class="nk-block-head-content">
                    <h3 class="nk-block-title page-title">Your apps</h3>
                    <div class="nk-block-des text-soft">
                        <p>You have total {{modules|length}} installed apps.</p>
                    </div>
                </div>
                {% if current_user.can(16) %}
                <div class="nk-block-head-content">
                    <div class="toggle-wrap nk-block-tools-toggle"><a href="#"
                            class="btn btn-icon btn-trigger toggle-expand mr-n1" data-target="pageMenu"><em
                                class="icon ni ni-menu-alt-r"></em></a>
                        <div class="toggle-expand-content" data-content="pageMenu">
                            <ul class="nk-block-tools g-3">
                                <li class="nk-block-tools-opt"><a href="#" class="btn btn-primary"><em
                                            class="icon ni ni-plus"></em><span>Add App</span></a></li>
                            </ul>
                        </div>
                    </div>
                </div>
                {% endif %}
            </div>
        </div>
        <div class="nk-block">
            <div class="row g-gs">
                {% for module in modules %}
                <div class="col-sm-6 col-xl-4">
                    <div class="card card-bordered h-100">
                        <div class="card-inner">
                            <div class="project">
                                <div class="project-head"><a href="/demo4/apps-kanban.html" class="project-title">
                                        <div class="user-avatar sq bg-purple">
                                            <span>{{module.name[0]}}</span>
                                        </div>
                                        <div class="project-info">
                                            <h6 class="title">{{module.name}}</h6><span
                                                class="sub-text">{{module.category.name}}</span>
                                        </div>
                                    </a>                                    
                                </div>
                                <div class="project-details">
                                    <p>{{module.long_description}}</p>
                                </div>
                                <a href="{{url_for('main.connect', id=module.id)}}" class="btn btn-wider btn-primary"><span>Connect</span><em
                                    class="icon ni ni-arrow-right"></em></a>
                            </div>
                        </div>
                    </div>
                </div>
                {% endfor %}
            </div>
        </div>
    </div>
    {% include "footer.html" %}
</div>
{% endblock %}

app/templates/main/set-up.html
{% extends "base.html" %}

{% block getting_started %}
<style>
    .bordered-focus {
        border-color: #6576ff;
        box-shadow: 0 0 0 3px rgb(101 118 255 / 10%);
    }

    #dv_start_now {
        display: none;
    }

    #dv_loading {
        display: none;
    }
</style>
{% if title == 'Getting Started | Teleios' %}
<div class="nk-content-body">
    <div class="nk-content-wrap">
        <div class="nk-block-head nk-block-head-sm">
            <div class="nk-block-between">
                <div class="nk-block-head-content">
                    <h2 class="nk-block-title fw-normal">Manage Your Databases</h2>
                </div>
            </div>
        </div>
        <div class="nk-block nk-block-lg">
            <div class="card card-preview">
                <div class="card-inner">
                    {% with messages = get_flashed_messages() %}
                    {% if messages %}
                    {% for message in messages %}
                    <div class="alert alert-primary" role="alert" style="text-align: center;">
                        {{message}}&nbsp;<a href="{{url_for('main.choose_apps')}}" class="alert-link">Start
                            with
                            a New Database Instance</a>.
                    </div>
                    {% endfor %}
                    {% endif %}
                    {% endwith %}
                </div>
            </div>
            <div class="card card-preview">
                <div class="card-inner">
                    <ul class="preview-btn-list preview-btn-list-fw">
                        <li class="preview-btn-item col-sm-6 col-lg-3"><span class="preview-title overline-title">Expava
                                Group</span><a href="#" class="btn btn-wider btn-primary"><span>Connect</span><em
                                    class="icon ni ni-arrow-right"></em></a></li>
                        <li class="preview-btn-item col-sm-6 col-lg-3"><span class="preview-title overline-title">Arnold
                                Nderitu</span><a href="#" class="btn btn-wider btn-primary"><span>Connect</span><em
                                    class="icon ni ni-arrow-right"></em></a></li>
                        <li class="preview-btn-item col-sm-6 col-lg-3"><span class="preview-title overline-title">Expava
                                Group Test</span><a href="#" class="btn btn-wider btn-primary"><span>Connect</span><em
                                    class="icon ni ni-arrow-right"></em></a></li>
                        <li class="preview-btn-item col-sm-6 col-lg-3"><span class="preview-title overline-title">Arnold
                                Nderitu Test</span><a href="#" class="btn btn-wider btn-primary"><span>Connect</span><em
                                    class="icon ni ni-arrow-right"></em></a></li>
                    </ul>
                </div>
            </div>
        </div>
    </div>
    {% include "footer.html" %}
</div>
{% endif %}
{% if title == 'New Database | Teleios' %}
<div id="dv_new_database" class="nk-content-body">
    <div class="nk-content-wrap">
        <div class="nk-block-head nk-block-head-sm">
            <div class="nk-block-between">
                <div class="nk-block-head-content">
                    <h2 class="nk-block-title fw-normal">Choose your Apps</h2>
                </div>
            </div>
        </div>
        {% for moduleCategory in moduleCategories %}
        <div class="nk-block nk-block-lg">
            <h5 class="title nk-block-title">{{moduleCategory.name}}</h5>
            <div class="row g-gs">
                {% for module in modules %}
                {% if module.category_id == moduleCategory.id %}
                <div class="col-lg-4">
                    <div id="dv-{{module.id}}" href="#" class="card card-bordered text-soft dv-module">
                        <div class="card-inner">
                            <div class="align-center justify-between">
                                <div class="g">
                                    <h6 id="title-{{module.id}}" class="title">{{module.name}}</h6>
                                    <p>{{module.short_description}}</p>
                                </div>
                                <div class="custom-control custom-checkbox">
                                    <input type="checkbox" class="custom-control-input check" id="check-{{module.id}}">
                                    <label class="custom-control-label" id="price-{{module.monthly_price_kes}}"></label>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                {% endif %}
                {% endfor %}                
            </div>
        </div>
        {% endfor %}
    </div>
    {% include "footer.html" %}
</div>
<div id="dv_start_now" class="nk-content-body">
    <div class="nk-content-wrap">
        <div class="components-preview wide-md mx-auto">
            <div class="nk-block-head nk-block-head-lg wide-sm">
                <div class="nk-block-head-content">
                    <div class="nk-block-head-sub"><a class="back" href="#"><em
                                class="icon ni ni-arrow-left"></em><span>Change apps selection</span></a></div>
                    <h2 class="nk-block-title fw-normal">Teleios | Get Started</h2>
                </div>
            </div><!-- .nk-block-head -->
            <div class="nk-block nk-block-lg">
                <div class="card card-preview">
                    <div class="card-inner">
                        <div class="preview-block">
                            <div class="row gy-4">
                                <div class="col-sm-6">
                                    <div class="form-group">
                                        <label class="form-label" for="fname">First Name</label>
                                        <div class="form-control-wrap">
                                            <input type="text" class="form-control" id="fname" placeholder="First Name">
                                        </div>
                                    </div>
                                </div>
                                <div class="col-sm-6">
                                    <div class="form-group">
                                        <label class="form-label" for="lname">Last Name</label>
                                        <div class="form-control-wrap">
                                            <input type="text" class="form-control" id="lname" placeholder="Last Name">
                                        </div>
                                    </div>
                                </div>
                                <div class="col-sm-6">
                                    <div class="form-group">
                                        <label class="form-label" for="email">Email</label>
                                        <div class="form-control-wrap">
                                            <input type="text" class="form-control" id="email" placeholder="Email">
                                        </div>
                                    </div>
                                </div>
                                <div class="col-sm-6">
                                    <div class="form-group">
                                        <label class="form-label" for="phneNumber">Phone Number</label>
                                        <div class="form-control-wrap">
                                            <input type="number" class="form-control" id="phneNumber"
                                                placeholder="Phone Number">
                                        </div>
                                    </div>
                                </div>
                                <div class="col-sm-6">
                                    <div class="form-group">
                                        <label class="form-label" for="company">Company Name</label>
                                        <div class="form-control-wrap">
                                            <input type="text" class="form-control" id="company"
                                                placeholder="Company Name">
                                        </div>
                                    </div>
                                </div>
                                <div class="col-sm-6">
                                    <div class="form-group">
                                        <label class="form-label" for="domain">Domain</label>
                                        <div class="form-control-wrap">
                                            <div class="form-text-hint"><span class="overline-title">.teleios.com</span>
                                            </div>
                                            <input type="url" class="form-control" id="domain" placeholder="example">
                                        </div>
                                    </div>
                                </div>
                                <div class="col-sm-12">
                                    <div class="alert alert-gray alert-icon"><em class="icon ni ni-alert-circle"></em>By
                                        Clicking on <strong>Start Now</strong>,
                                        you accept our <a href="">Subscription Agreement</a> and <a href="">Privacy
                                            Policy</a></div>
                                </div>
                                <div class="col-sm-6">
                                    <div class="form-group">
                                        <div class="form-control-wrap">
                                            <a href="#" class="back btn btn-wider btn-secondary">
                                                <em class="icon ni ni-arrow-left"></em>
                                                <span style="margin-left: 0%">Change apps selection</span>
                                            </a>
                                        </div>
                                    </div>
                                </div>
                                <div class="col-sm-6">
                                    <div class="form-group">
                                        <div class="form-control-wrap">
                                            <a href="#" class="btn btn-wider btn-primary start-now"><span>Start
                                                    Now</span><em class="icon ni ni-arrow-right"></em></a>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div><!-- .card-preview -->
            </div><!-- .nk-block -->
        </div><!-- .components-preview -->
    </div>
    <!-- footer @s -->
    {% include "footer.html" %}
    <!-- footer @e -->
</div>
<div id="dv_loading" class="nk-content-body">
    <div class="nk-content-wrap">
        <div class="components-preview wide-md mx-auto">
            <div class="nk-block nk-block-lg">
                <div class="nk-block-head">
                    <div class="nk-block-head-content">
                        <h4 class="title nk-block-title">Building your Teleios apps</h4>
                        <p>We'll be ready shortly.
                        </p>
                    </div>
                </div>
                <div class="card card-preview">
                    <div class="card-inner">
                        <div class="progress">
                            <div class="progress-bar progress-bar-striped progress-bar-animated" data-progress="75"
                                style="width: 75%;"></div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    {% include "footer.html" %}
</div>

{% endif %}

{% include "modals/installing.html" %}
{% endblock %}